/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../include/jni.h"

#ifndef _Included_be_cloudns_edebe_util_jni_NativeReflectionUtils
#define _Included_be_cloudns_edebe_util_jni_NativeReflectionUtils
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jclass JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_defineClass(JNIEnv *env, jclass thisClass, jstring name, jobject loader, jbyteArray data, jint offset, jint length);

JNIEXPORT jclass JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_findClass(JNIEnv *env, jclass thisClass, jstring name);

JNIEXPORT jobject JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getObjectField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig);

JNIEXPORT jboolean JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getBooleanField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig);

JNIEXPORT jbyte JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getByteField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig);

JNIEXPORT jchar JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getCharField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig);

JNIEXPORT jshort JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getShortField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig);

JNIEXPORT jint JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getIntField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig);

JNIEXPORT jlong JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getLongField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig);

JNIEXPORT jfloat JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getFloatField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig);

JNIEXPORT jdouble JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getDoubleField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setObjectField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig, jobject value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setBooleanField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig, jboolean value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setByteField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig, jbyte value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setCharField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig, jchar value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setShortField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig, jshort value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setIntField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig, jint value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setLongField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig, jlong value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setFloatField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig, jfloat value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setDoubleField(JNIEnv *env, jclass thisClass, jclass clazz, jobject object, jstring name, jstring sig, jdouble value);

JNIEXPORT jobject JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getStaticObjectField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig);

JNIEXPORT jboolean JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getStaticBooleanField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig);

JNIEXPORT jbyte JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getStaticByteField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig);

JNIEXPORT jchar JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getStaticCharField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig);

JNIEXPORT jshort JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getStaticShortField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig);

JNIEXPORT jint JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getStaticIntField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig);

JNIEXPORT jlong JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getStaticLongField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig);

JNIEXPORT jfloat JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getStaticFloatField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig);

JNIEXPORT jdouble JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_getStaticDoubleField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setStaticObjectField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig, jobject value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setStaticBooleanField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig, jboolean value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setStaticByteField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig, jbyte value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setStaticCharField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig, jchar value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setStaticShortField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig, jshort value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setStaticIntField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig, jint value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setStaticLongField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig, jlong value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setStaticFloatField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig, jfloat value);

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_NativeReflectionUtils_setStaticDoubleField(JNIEnv *env, jclass thisClass, jclass clazz, jstring name, jstring sig, jdouble value);

#ifdef __cplusplus
}
#endif
#endif
