/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../include/jni.h"

#ifndef _Included_be_cloudns_edebe_util_jni_JavaUtilsNative
#define _Included_be_cloudns_edebe_util_jni_JavaUtilsNative
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_be_cloudns_edebe_util_jni_JavaUtilsNative_initialize(JNIEnv *env, jclass thisClass);

jint ThrowNewOutOfMemoryError(JNIEnv *env, const char *msg);

#ifdef __cplusplus
}
#endif
#endif
