/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../include/jni.h"

#ifndef _Included_pers_edebe_util_jni_NativeProcessUtils
#define _Included_pers_edebe_util_jni_NativeProcessUtils
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_pers_edebe_util_jni_NativeProcessUtils_readProcessMemory(JNIEnv *env, jclass thisClass, jlong pid, jlong address);

JNIEXPORT void JNICALL Java_pers_edebe_util_jni_NativeProcessUtils_writeProcessMemory(JNIEnv *env, jclass thisClass, jlong pid, jlong address, jlong value);

#ifdef __cplusplus
}
#endif
#endif
