/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../include/jni.h"

#ifndef _Included_pers_edebe_util_jni_EdebeUtilsNative
#define _Included_pers_edebe_util_jni_EdebeUtilsNative
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_pers_edebe_util_jni_EdebeUtilsNative_initialize(JNIEnv *env, jclass thisClass);

jint ThrowNewOutOfMemoryError(JNIEnv *env, const char *msg);

#ifdef __cplusplus
}
#endif
#endif
